// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pitqelftjafwycbfecug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpdHFlbGZ0amFmd3ljYmZlY3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzIzMDYsImV4cCI6MjA3Mzk0ODMwNn0.btlHUn3Tp1R1DQqTlbq6GqlCwsLB7w70xHnZWOtfCn0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});